name: Django CI

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      mongodb:
        image: mongo:3.4.23
        env:
          MONGO_INITDB_DATABASE: decide
        ports:
          - 27017:27017
        options: --health-cmd mongo --health-interval 10s --health-timeout 5s --health-retries 5

      ldap:
        image: carvilgar1us/decideldap
        ports:
          - 389:389

    steps:
      - uses: actions/checkout@v2
      - name: Install linux dependencies
        run: |
          sudo apt-get install build-essential python3-dev python2.7-dev libldap2-dev libsasl2-dev tox lcov valgrind
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install codacy-coverage
      - name: Copy local_settings
        run: |
          cp ./decide/local_settings.example.py ./decide/local_settings.py
      - name: Migrate
        run: |
          cd decide
          python manage.py makemigrations
          python manage.py migrate
      - name: Test administration module
        run: |
          cd decide
          coverage run --branch --source=./administration/ ./manage.py test administration --keepdb -v 2
          coverage xml
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: decide/coverage.xml
