name: Django CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        node-version: [16.13.0, 14.15.0]

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: decide
        ports:
          - 27017:27017
        options: --health-cmd mongo --health-interval 10s --health-timeout 5s --health-retries 5

      ldap-decide:
        image: 'carvilgar1us/ldapdecide'
        ports:
          - 389:389

    steps:
      - uses: actions/checkout@v2
      - name: Install linux dependencies
        run: |
          sudo apt-get install build-essential python3-dev python2.7-dev libldap2-dev libsasl2-dev tox lcov valgrind libpq-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install codacy-coverage
      - name: Copy local_settings
        run: |
          cp ./decide/local_settings.example.py ./decide/local_settings.py
      - name: Migrate
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          cd decide
          python manage.py flush --noinput
          python manage.py sqlflush
          python manage.py makemigrations
          python manage.py migrate
      - name: Test
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          cd decide
          coverage run --source . ./manage.py test --settings=decide.test_settings --noinput -v 2
          coverage xml
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: decide/coverage.xml
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install decide_panel dependencies
        run: cd decide_panel && npm install
      - name: Deploy decide
        run: |
          cd decide && 
          python manage.py runserver --settings=decide.test_settings &
      - name: Deploy decide_panel
        run: |
          cd decide_panel && 
          npm run start:local &
      - name: Test React app
        run: cd decide_panel && npm run test:e2e
      - name: Codacy Coverage Reporter React
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: decide_panel/coverage/clover.xml
